apiVersion: batch/v1
kind: Job
metadata:
  name: job3
spec:
  # backoffLimit: 2
  activeDeadlineSeconds: 15
  template:
    spec:
      containers:
      - name: job1 
        image: alpine
        command: ["sh", "-c"]
        args: ["cat/tec/puff.txt"]
      restartPolicy: Never