apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: desa-req-auth
spec:
  groups: 
  - system:authenticated
  request: $(cat desa1.csr | base64 | tr -d '\n')
  usages:
  - digital signature
  - key encupherment
  - server auth
  - client auth