version: '3.9'
services:
  wordpress:
    image: wordpress  
    container_name: wordpress
    restart: always
    ports:
      - "9090:80"
    environment:
      - WORDPRESS_DB_HOST=db-host
      - WORDPRESS_DB_USER=wp-user
      - WORDPRESS_DB_PASSWORD=lepanto
      - WORDPRESS_DB_NAME=wp-db
    depends_on:
      - db-wp
    networks:
      - wp-network
    profiles:
      - development
      - production

### BD DESARROLLO ###
  db-wp:
    image: mysql
    container_name: db-development
    restart: always
    environment:
      - MYSQL_DATABASE=wp-db
      - MYSQL_USER=wp-user
      - MYSQL_PASSWORD=lepanto
      - MYSQL_ROOT_PASSWORD=lepanto
    networks:
      wp-network:
        aliases:
          - db-host
    profiles:
      - development
### BD PRODUCCION ###
  db-wp-prod:
    image: mysql
    container_name: db-production
    restart: always
    environment:
      - MYSQL_DATABASE=wp-db
      - MYSQL_USER=wp-user
      - MYSQL_PASSWORD=lepanto
      - MYSQL_ROOT_PASSWORD=lepanto
    networks:
      wp-network:
        aliases:
          - db-host
    profiles:
      - production
networks:
  wp-network:


