apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-disk-1
spec:
  storageClassName: "sc-disk-1"
  capacity:
    storage: 10
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: pvc-disk-1
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: projects/modified-math-371610/zones/us-central1-a/disks/disk-1
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: pvc-disk-1
spec:
  storageClassName: "sc-disk-1"
  volumeName: pv-disk-1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10