apiVersion: v1
kind: Pod
metadata:
  name: apache1
spec:
  containers:
  - name: apache1
    image: httpd
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: equipo
                operator: In
                values:
                - desarrollo-web
                - desarrollo-python
