apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-job1
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: job1 
            image: alpine
            command: ["sh", "-c"]
            args: ["echo Estas en la maquina $(uname -n)"]
          restartPolicy: Never