apiVersion: v1
kind: Pod
metadata:
  name: busybox-never
  labels:
    name: busybox1
spec:
  containers:
  - name: busybox-never
    image: busybox
    command: ['sh', '-c', 'echo Ejemplo de pod fallado && exit 1']
  restartPolicy: Never
