apiVersion: v1
kind: Pod
metadata:
  name: busybox-on-failure
  labels:
    name: busybox1
spec:
  containers:
  - name: busybox-on-failure
    image: busybox
    command: ['sh', '-c', 'echo Ejemplo de pod fallado && exit 1']
  restartPolicy: OnFailure
